comment:
  layout: "header, diff, flags, components"

component_management:
  individual_components:
    - component_id: app  # this is an identifier that should not be changed
      name: app  # this is a display name, and can be changed freely
      paths:
        - app