version: "3"

services:
  skydaddy:
    build:
      context: app
    ports:
      - "5000"
    volumes:
      - ./app/UPLOADS:/app/UPLOADS
      - ./app/PERMA:/app/PERMA

  ngnix:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - skydaddy
    ports:
      - "80:80"

#volumes:
#  shared_UPLOAD:
