version: "3.9"

services:
  skydaddy:
    build:
      context: app
    ports:
      - "5000"
    deploy:
      replicas: 3
    volumes:
      - type: bind
        source: ./app/UPLOADS
        target: /app/UPLOADS

  ngnix:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - skydaddy
    ports:
      - "80:80"
