version: "3"

services:
  skydaddy:
    build:
      context: app
    ports:
      - "5000"
    volumes:
      - sharedUPLOAD:/app/UPLOADS
      - sharedPERMA:/app/PERMA

  ngnix:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - skydaddy
    ports:
      - "80:80"

volumes:
  sharedUPLOAD:
    external: true
  sharedPERMA:
    external: true
